// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovujyuktfunvljykmbpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92dWp5dWt0ZnVudmxqeWttYnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzQzMDQsImV4cCI6MjA2NDUxMDMwNH0.ke5l3sZfgYgC0B03pYUd9f_ufamhHQg51kh6zhmtNLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);